//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOCAMM.Controllers.Productos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int usuarioId { get; set; }
        public string Nombre { get; set; }
        public string CorreoElectronico { get; set; }
        public string nombreus { get; set; }
        public string pass { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
