
 * IMPORTANTE: el uso de este software indica que acepta los términos
    * encontrado en http://www.adobe.com/products/eulas/tou_typekit NOTA QUE SU
 * LOS DERECHOS A ESTE SOFTWARE SON LIMITADOS.ÚSELO BAJO SU PROPIO RIESGO.Para licencia de fuente
    * información, ver el archivo CSS cargado por este JavaScript.
 * /
if (!window.Typekit) window.Typekit = {}; window.Typekit.config = { "f": "// use.edgefonts.net/c/5e84d7/1w;montserrat,2,2cm5Ph:W:n4; source-sans-pro, 2,2clybm: W: n2 / {format} {/ extras *} ", " fi ": [16353, 17275], " fn ": [" montserrat ", [" n4 "], " source-sans-pro ", [" n2 "]], " ht ": " tk ", " js ": " 1.14.9 ", " p ": " // p.typekit.net/p.gif?s = 4 & h = {host} & f = 16353.17275 & app = {app} & _ = {_} ", " ps ": 4 };
; (función(ventana, documento, indefinido) {
    if (!document.querySelector) { document.documentElement.className + = "wf-inactive"; return; } función aa(a, b, c) { return a.call.apply(a.bind, argumentos) } función ba(a, b, c) { si(!a) arroja Error(); if (2 < argument.length) { var d = Array.prototype.slice.call(argumentos, 2); return function () { var c = Array.prototype.slice.call(argumentos); Array.prototype.unshift.apply(c, d); return a.apply(b, c) } } return función() { return a.apply(b, argumentos) } } función k(a, b, c) { k = Function.prototype.bind && - 1! = Function.prototype.bind.toString().indexOf("código nativo") ? aa : ba; return k.apply(nulo, argumentos) } var m = Date.now || function () { return + new Date }; function ca() { this.P = this.R = this.I = this.N = this.O = !0 }; function da() { var a = [{ name: "font-family", valor: nc[q + 1] }]; this.g = [nc[q]]; this.b = a } función ea(a) { para(var b = agjoin(","), c = [], d = 0; d < ablength; d++) { var e = ab[d]; c.push(e.name + ":" + e.value + ";") } return b + "{" + c.join("") + "}" }; función fa(a) { this.b = a } fa.prototype.toString = function () { return encodeURIComponent(ga(this.b)) }; función ha(a, b) { this.g = a; this.b = b } ha.prototype.toString = function () { for (var a = [], b = 0; b < this.b.length; b++) para(var c = this.b[b], d = cG(), c = cG(this.g), e = 0; e < d.length; e++) { var f; a: { para(f = 0; f < c.length; f++) if (d[e] === c[f]) { f = !0; break a } f = !1 } a.push(f ? 1 : 0) } a = a.join(""); a = a.replace(/ ^ 0 + /, ""); b = []; para(d = a.length; 0 < d; d - = 4) b.unshift(parseInt(a.slice(0 > d - 4 ? 0 : d - 4, d), 2).toString(16)) return b.join("") }; función ia(a, b) { this.b = a; this.g = b } ia.prototype.G = function () { return this.g }; function ja(a) { this.b = a } function ka(a, b) { return b }; function la() { this.b = this.g = -1 } la.prototype.start = function () { this.g = (nueva fecha) .getTime(); this.b = -1 }; var t = { V: "a", $: "d ", U: " i ", W: " j ", T: " k ", Z: " l ", NINGUNO: " x " }; var v = {}; va = vd = vl = vj = función() { return [] }; vi = función(a, b, c) { return [new fa(a), new ha(b, c)] }; vk = function (a) { return [new fa(a)] }; función ma(a, b, c) { return v[b](a, b, c) }; var na = {};
    na.i = nueva ja(función(a, b, c) { para(var d = 0; d<b.length; d + = 1) { var e = b[d], f; f = e; f = a.replace(/ (- 1 | -2) $ /, "").slice(0, 28) + "-" + f; c.push(new ia(f, [e])) } a = {}; para(e = 0; e < b.length; e++) c = b[e], d = c.charAt(1), (a[d] || (a[d] = [])).empuje(c); c = [[4, 3, 2, 1, 5, 6, 7, 8, 9], [7, 8, 9, 6, 5, 4, 3, 2, 1]]; d = []; para(e = 0; e < c.length; e++) { f = c[e]; para(var g = 0; g < f.length; g++) { var h = f[g]; if (a[h]) { d = d.concat(a[h]); break } } } c = d; d = {}; a = []; para(e = 0; e < c.length; e++) f = c[e], d[f] || (d[f] = !0, a.push(f)); c = []; para(d = 0; d < b.length; d++ ) para(e = b[d], f = 0; f < a.length; f++) g = a[f],
        g == e && c.push(g); return c
}); function oa(a) { this.b = a } oa.prototype.s = function (a, b) { var c = a || {}, d = this.b.replace(/ \ {\ / ? ([^ *}] *) (\ *?) \} / g, function (a, b, d) {return d && c [b]? "/" + c [b] .join (" / "): c [b] || ""}); d.match (/ ^ \ / \ //) && (d = (b? "http: ": "https: ") + d); devolver d.replace (/ \ / * \? * ($ | \?) /," $ 1 ")}; función pa (a, b) {para (var c = [], d = 0; d <b.length; d ++) c.push (b [d] .toString ()); return {formato: a, extras: c}}; función qa (a) {var b = nueva Imagen (1, 1), c =! 1; b.src = a; b.onload = function () {c =! 0; b.onload = null}; setTimeout (function () {c || (b.src = "about: en blanco ", b.onload = null)}, 3E3)}; función w (a, b, c, d, e, f, g) {this.b = a; this.B = b; this.F = c; this.D = d; this.v = e; this.o = f; this.M = g} w.prototype.getName = function () {return this.b}; function x (a, b, c , d) {this.b = null! = a? a: null; this.g = null! = b? b: null; this.h = null! = c? c: null; this.s = null! = d? d: null} var ra = / ^ ([0-9] +) (?: [\ ._-] ([0-9] +))? (?: [\ ._ -] ([0-9] +))? (?: [\ ._ + -]? (. *))? $ /; Función y (a, b) {return ab> bb || ab === bb && a.g> bg || ab === bb && a.g === bg && a.h> bh? 1: ab <bb || ab === bb && a.g <bg || ab === bb && a.g == = bg && a.h <bh? -1: 0} función A (a, b) {return-1 === y (a, b)} función B (a, b) {return 0 === y (a, b) || 1 === y (a, b)} función sa (a, b) {return 0 === y (a, b) || -1 === y (a, b)} función ta (a, b) {return 0 === y (a, b)}b)} función sa (a, b) {return 0 === y (a, b) || -1 === y (a, b)} función ta (a, b) {return 0 === y (a, b)}b)} función sa (a, b) {return 0 === y (a, b) || -1 === y (a, b)} función ta (a, b) {return 0 === y (a, b)}
x.prototype.toString = function () { return [this.b, this.g || "", this.h || "", this.s || ""].join("") }; function C(a) { a = ra.exec(a); var b = nulo, c = nulo, d = nulo, e = nulo; a && (nulo! == a[1] && a[1] && (b = parseInt(a[1], 10)), null! == a[2] && a[2] && (c = parseInt(a[2], 10)), null! == a[3] && a[3] && (d = parseInt(a[3], 10)), null! == a[4] && a[4] && (/ ^ [0-9] + $ /.test(a[4]) ? e = parseInt(a[4], 10) : e = a[4])); devolver nuevo x(b, c, d, e) }; función ua(a) { return "Safari" === a.getName() && "AppleWebKit" === aF || "Desconocido" === a.getName() && "AppleWebKit" === aF && ("iPhone" === av || "iPad" === av || "iPod" === av) } función va(a) { return "Chrome" === a.getName() && B(aB, nuevo x(6)) && sa(aB, nueva función x(35)) } wa(a) { return "Chrome" === a.getName() && B(aB, nueva x(36)) } función xa(a) { return "BuiltinBrowser" === a.getName() }; función D(a) { return "Windows" === av } function ya(a) { return D(a) && B(ao, nueva x(6, 1)) } función E(a) { return D(a) && ta(ao, nuevo x(5, 1)) || D(a) && ta(ao, nuevo x(5, 2)) || D(a) && ta(ao, nuevo x(6), 0)) || ya(a) } función F(a) { return "Macintosh" === av && (B(ao, nuevo x(10, 4)) || null === aob) } función za(a, b) { return bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(4, 2)) && A(ao, nuevo x(5)) } función Aa(a, b) { return bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(5)) } función D(a) { return "Windows" === av } función ya(a) { return D(a) && B(ao, nueva x(6, 1)) } función E(a) { return D(a) && ta(ao, nuevo x(5, 1)) || D(a) && ta(ao, nuevo x(5, 2)) || D(a) && ta(ao, nuevo x(6, 0)) || ya(a) } función F(a) { return "Macintosh" === av && (B(ao, nuevo x(10, 4)) || null === aob) } function za(a, b) { return bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(4, 2)) && A(ao, nuevo x(5)) } función Aa(a, b) { devuelva bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(5)) } función D(a) { return "Windows" === av } función ya(a) { return D(a) && B(ao, nueva x(6, 1)) } función E(a) { return D(a) && ta(ao, nuevo x(5, 1)) || D(a) && ta(ao, nuevo x(5, 2)) || D(a) && ta(ao, nuevo x(6, 0)) || ya(a) } función F(a) { return "Macintosh" === av && (B(ao, nuevo x(10, 4)) || null === aob) } function za(a, b) { return bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(4, 2)) && A(ao, nuevo x(5)) } función Aa(a, b) { devuelva bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(5)) } nueva x(10, 4)) || null === aob)} función za(a, b) { return bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(4, 2)) && A(ao, nueva x(5)) } función Aa(a, b) { return bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(5)) } nueva x(10, 4)) || null === aob)} función za(a, b) { return bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(4, 2)) && A(ao, nueva x(5)) } función Aa(a, b) { return bO && ("iPhone" === av || "iPod" === av) && B(ao, nuevo x(5)) }
función Ba(a, b) { return bN && "iPad" === av && B(ao, nuevo x(4, 2)) && A(ao, nuevo x(5)) } función Ca(a, b) { return bN && " iPad " === av && B(ao, nueva x(5)) } función J(a, b) { return bI && " Android " === av } function Da(a, b) { return J(a, b) && B(ao, nueva x(2, 2)) && A(ao, nueva x(3, 1)) } función Ea(a, b) { return J(a, b) && B(ao, nueva x(3, 1)) && A(ao, nueva x(4, 1)) } función K(a) { return "Linux" === av || "Ubuntu" === av }; var Fa = {
    a: function (a, b) { return "Safari" === a.getName() && "AppleWebKit" === aF && B(aD, nuevo x(525, 13)) && A(aD, nuevo x(534, 50)) && (E(a) || F(a)) || xa(a) && (Da(a, b) || J(a, b) && B(ao, nuevo x(4, 1))) || bI && "Seda" = == a.getName() && A(aB, nuevo x(2)) && (Da(a, b) || F) || bI && "Seda " === a.getName() && B(aB, nuevo x(2)) && J(a, b) && B(ao, nuevo x(4, 1)) || ua(a) && (Ba(a, b) || za(a, b)) || va(a) && (Ba(a, b) || za(a, b)) || wa(a) && (Ba(a, b) || za(a, b)) || "AdobeAIR" === a.getName() && B(aB, nuevo x(2, 5)) && (D(a) && null === aob || K(a) | | F(a)) }, d: function (a, b) {
        return va(a) && (E(a) ||
            K(a) || F(a) || J(a, b) || "CrOS" === av || "CrKey" === av || Ca(a, b) || Aa(a, b)) || wa(a) && (Ca(a, b) || Aa(a, b)) || "Gecko" === aF && 1 === y(aD, nuevo x(1, 9, 1)) && sa(aD, nuevo x(38)) && (E(a) || K(a) || F(a) || J(a, b)) || "Safari" === a.getName() && "AppleWebKit" === aF && B(aD, nuevo x(534, 50)) && (E(a) || F(a)) || ua(a) && (Ca(a, b) || Aa(a, b)) || "Opera" === a.getName() && B(aB, nuevo x(11, 10)) && sa(aB, nuevo x(22)) && (E(a) || K(a) || F(a) || J(a, b)) || "MSIE" === a.getName() && 9 <= aM && (ya(a) || D(a) && ta(ao, nuevo x(6, 0))) || "Edge" === a.getName() && ya(a) || "MSIE" === a.getName() && b.R &&
            "Windows Phone" === av && B(ao, nuevo x(8)) || xa(a) && (bP && "BlackBerry" === av && B(ao, nuevo x(10)) || K(a))
    }, j: función(a, b) { devolver xa (a) && Ea(a, b) || bI && "Seda" === a.getName() && B(aB, nuevo x(2)) && (Ea(a, b) || K(a))}, i: function (a) { return "MSIE" === a.getName() && B(aB, nuevo x(6, 0)) && (void 0 === aM || 9 > aM) && E(a) }, l: function (a, b) { return wa(a) && (E(a) || K(a) || F(a) || J(a, b) || "CrOS" === av || "CrKey" === av) || "Gecko" === aF && B(aD, nuevo x(39)) && (E(a) || K(a) || F(a) || J(a, b)) || "Opera" === a.getName() && B(aB, nuevo x(23)) && (E(a) || K(a) || F(a) || J(a, b)) },
x: function () { return !1 }}; var Ga = new w("Unknown", new x, "Unknown", new x, "Unknown", new x, void 0); function L(a) { var b = M(ab, / (iPod | iPad | iPhone | Android | Windows Phone | BB \ d {2} | BlackBerry) /, 1); if (""! == b) return / BB \ d {2} /.test(b) && (b = "BlackBerry"), b; a = M(ab, /(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/, 1); return "" !== a ? ("Mac_PowerPC" == a ? a = "Macintosh" : "PlayStation" == a && (a = "Linux"), a) : "Desconocido" }
función N(a) { var b = M(ab, / (OS X | Windows NT | Android) ([^;)] +) /, 2); if (b || (b = M(ab, / Windows Phone (OS)? ([^;)] +) /, 2)) || (b = M(ab, / (iPhone)? OS ([\ d _] +) /, 2))) return b; if (b = M(ab, / (?: Linux | CrOS | CrKey) ([^;)] +) /, 1)) para(var b = b.split(/ \ s /), c = 0; c < b.length; c + = 1) if (/ ^ [\ d \ ._] + $ /.test(b[c])) return b[c]; return (a = M(ab, / (BB \ d {2} | BlackBerry). *? Versión \ /([^ \ s] *) /, 2)) ? a : "Desconocido" }
función Ha() {
    var a = O, b = "Desconocido", c = C(M(ab, / Presto \ /([\ d \ w \.] +) /, 1)), d = C(N(a)), e = P(ag); null! == cb ? b = "Presto" : (- 1! = abindexOf("Gecko") && (b = "Gecko"), c = C(M(ab, / rv: ([^ \)] +) /, 1))); if (-1! = abindexOf("Opera Mini /")) { var f = C(M(ab, / Opera Mini \ /([\ d \.] +) /, 1)); devolver nuevo w("OperaMini", f, b, c, L(a), d, e) } if (-1! = abindexOf("Version / ") && (f = C(M(ab, / Version \ /([\ d \.] +) /, 1)), null! == fb)) devuelve new w(" Opera ", f, b, c, L(a), d, e); f = C(M(ab, / Opera [\ /] ([\ d \.] +) /, 1)); return null! == fb ? new w("Opera", f, b, c, L(a), d, e) : nuevo w("Opera",
        nuevo x, b, c, L(a), d, e)
}
función Ia() {
    var a = O, b = L(a), c = C(N(a)), d = C(M(ab, / AppleWeb (?: K | k) it \ /([\ d \.\ +] +) /, 1)), e = "Desconocido", f = nuevo x, f = "Desconocido"; / OPR \ /[\ d.]+ /. test (ab)? e = "Opera": - 1! = AbindexOf ("Chrome") || -1! = AbindexOf ("CrMo") || -1! = AbindexOf ("CriOS")? E = "Chrome": / Silk \ / \ d /.test(ab) ? e = "Seda" : "BlackBerry" == b || "Android" == b ? e = "BuiltinBrowser" : - 1! = abindexOf("PhantomJS") ? e = "PhantomJS " : -1! = AbindexOf(" Safari ") ? E = " Safari " : - 1! = AbindexOf(" AdobeAIR ") ? E = " AdobeAIR " : - 1! = AbindexOf(" PlayStation ") && (e = "BuiltinBrowser"); "BuiltinBrowser" ==
        e ? f = "Desconocido" : "Seda" == e ? f = M(ab, / Silk \ /([\ d \ ._] +) /, 1) : "Chrome" == e ? f = M(ab, / (Chrome | CrMo | CriOS) \ /([\ d \.] +) /, 2) : - 1! = abindexOf("Version /") ? f = M(ab, / Version \ /([\ d \.\ w] +) /, 1) : "AdobeAIR" == e ? f = M(ab, / AdobeAIR \ /([\ d \.] +) /, 1) : "Opera" = = e ? f = M(ab, / OPR \ /([\ d.] +) /, 1) : "PhantomJS" == e && (f = M(ab, / PhantomJS \ /([\ d.] + ) /, 1)); f = C(f); devolver nuevo w(e, f, "AppleWebKit", d, b, c, P(ag))
} función M(a, b, c) { return (a = a.match(b)) && a[c] ? a[c] : "" } función P(a) { si(a.documentMode) devuelve a.documentMode }; función Ja(a) { this.b = a || "-" } Ja.prototype.s = función(a) { para(var b = [], c = 0; c < argumentos.longitud; c++) b.push(argumentos[c].replace(/ [\ W _] + / g, "").ToLowerCase()); return b.join(this.b) }; var Ka = !!window.FontFace; function La(a, b, c, d) { b = abcreateElement(b); if (c) para(var e in c) c.hasOwnProperty(e) && ("style" == e ? b.style.cssText = c[e] : b.setAttribute(e, c[e])); d && b.appendChild(abcreateTextNode(d)); return b } función Ma(a, b, c) { a = abgetElementsByTagName(b)[0]; a || (a = document.documentElement); a.insertBefore(c, a.lastChild) }
function Na(a, b) { abbody ? b() : abaddEventListener ? abaddEventListener("DOMContentLoaded", b) : abattachEvent("onreadystatechange", function () { "interactive"! = abreadyState && "complete"! = abreadyState || b() }) } función Oa(a) { a.parentNode && a.parentNode.removeChild(a) }
función Q(a, b, c) { b = b || []; c = c || []; para(var d = a.className.split(/ \ s + /), e = 0; e < b.length; e + = 1) { para(var f = !1, g = 0; g < d.length; g + = 1) if (b[e] === d[g]) { f = !0; break } f || d.push(b[e]) } b = []; para(e = 0; e < d.length; e + = 1) { f = !1; para(g = 0; g < c.length; g + = 1) if (d[e] === c[g]) { f = !0; break } f || b.push(d[e]) } a.className = b.join("").replace(/ \ s + / g, "").replace(/ ^ \ s + | \ s + $ /, "") } función Pa(a, b) { for (var c = a.className.split(/ \ s + /), d = 0, e = c.length; d < e; d++) si(c[d] == b) return !0; return !1 }
función Qa(a) { if ("(string" === typeof am) return am; var b = aglocation.protocol; "about:" == b && (b = ahlocation.protocol); return "https:" == b ? "https:" : "http:" } function ga(a) { return aglocation.hostname || ahlocation.hostname }
función Ra(a, b, c, d) {
    función e() { G && p && z && (G(H), G = null) } función f(a) { para(var c = 0; c < l.length; c++) if (l[c].href && - 1! == l[c].href.indexOf(b)) { a(); return } setTimeout(function () { f(a) }, 0) } función g(a) { para(var c = 0; c < l.length; c++) if (l[c].href && - 1! == l[c].href.indexOf(b) && l[c].media) { var d = l[c].media; if ("all" === d || d.mediaText && "all" === d.mediaText) { a(); return } } setTimeout(function () { g(a) }, 0) } var h = La(a, "link", { rel: "hoja de estilo", href: b, media: d ? "only x" : "all" }), l = abstyleSheets, p = !1, z = !D, H = nulo, G = c || nulo; Ka ? (H.onload =
        function () { p = !0; e() }, h.onerror = function () { p = !0; H = Error("Falló la hoja de estilo"); e() }) : setTimeout(function () { p = !0; e() }, 0); Ma(a, "head", h); d && f(function () { h.media = "all"; g(function () { z = !0; mi() }) })
}
función Sa(a, b, c) { var d = abgetElementsByTagName("head")[0]; if (d) { var e = La(a, "script", { src: b }), f = !1; e.onload = e.onreadystatechange = function () { f || this.readyState && "loaded"! = this.readyState && "complete"! = this.readyState || (f = !0, c && c(null), e.onload = e.onreadystatechange = null, "HEAD" == e.parentNode.tagName && d.removeChild(e)) }; d.appendChild(e); setTimeout(function () { f || (f = !0, c && c(Error("Tiempo de espera de carga del script"))) }, 5E3) } }; función Ta(a, b) { this.b = a; this.h = agdocument.documentElement; this.u = b; this.g = new Ja("-"); this.w = !1! == b.events; this.m = !1! == b.classes } function Ua(a) { if (am) { var b = Pa(ah, ags("wf", "activo")), c = [], d = [ags("wf", "cargando")]; b || c.push(ags("wf", "inactivo")); Q(ah, c, d) } R(a, "inactiva ") } función R(a, b, c) { si(aw && a.u[b]) si(c) au[b](c.getName(), S(c)) else ([b]) ) }; función T(a, b) { this.h = a; this.g = 4; this.b = "n"; var c = (b || "n4").match(/ ^ ([nio ]) ([1-9]) $ / i); c && (this.b = c[1], this.g = parseInt(c[2], 10)) } T.prototype.getName = function () { return this.h }; función Va(a) { return Wa(a) + "" + (a.g + "00") + "300px" + Xa(ah) } función Xa(a) { var b = []; a = a.split(/, \ s * /); para(var c = 0; c < a.length; c++) { var d = a[c].replace(/ ['"] / g, " "); - 1! = D.indexOf(" ") || / ^ \ d /.test(d) ? B.push(" '" + d + "' ") : b.push(d) } return b.join(",") } función S(a) { return a.b + ag } match(/ ^ ([nio]) ([1-9]) $ / i); c && (this.b = c[1], this.g = parseInt(c[2], 10))} T.prototype.getName = function () { return this.h }; function Va(a) { return Wa(a) + "" + (a.g + "00") + "300px" + Xa(ah) } function Xa(a) { var b = []; a = a.split(/, \ s * /); para(var c = 0; c < a.length; c++) { var d = a[c].replace(/ [ '"] / g, " "); - 1! = d.indexOf(" ") || / ^ \ d /.test(d) ? b.push("' " + d + " '") : b.push(d) } return b.join(",") } función S(a) { return a.b + ag } match(/ ^ ([nio]) ([1-9]) $ / i); c && (this.b = c[1], this.g = parseInt(c[2], 10))} T.prototype.getName = function () { return this.h }; function Va(a) { return Wa(a) + "" + (a.g + "00") + "300px" + Xa(ah) } function Xa(a) { var b = []; a = a.split(/, \ s * /); para(var c = 0; c < a.length; c++) { var d = a[c].replace(/ [ '"] / g, " "); - 1! = d.indexOf(" ") || / ^ \ d /.test(d) ? b.push("' " + d + " '") : b.push(d) } return b.join(",") } función S(a) { return a.b + ag }) || / ^ \ d /.test(d) ? b.push("'" + d + "'") : b.push(d)} devolver b.join(",")} función S(a) { return a.b + ag }) || / ^ \ d /.test(d) ? b.push("'" + d + "'") : b.push(d)} devolver b.join(",")} función S(a) { return a.b + ag }
función Wa(a) { var b = "normal"; "o" === ab ? b = "oblicuo" : "i" === ab && (b = "cursiva"); return b }; función Ya(a, b) { this.b = a; this.m = b; this.h = {}; this.g = {} } Ya.prototype.G = function (a) { return a ? (this.h[a] || this.m).slice(0) : this.m.slice(0) }; función Za(a, b, c) { para(var d = [], e = absplit(",")[0].replace(/ "| '/ g, " "), f = aG(), g, h = [], l = {}, p = 0; p < f.length; p++) g = f[p], 0 < g.length && !l[g] && (l[g] = !0, h.push(g)); c = cb ? cb(e, h, d) : h; ah[b] = c; ag[b] = d }
función $ a(a, b) { para(var c = aG(b), d = ag[b] || [], e = [], f = 0; f < c.length; f++) e.push(nueva T(ab, c[f])) para(f = 0; f < d.length; f++) if (c = d[f].b, c! == ab) para(var g = d[f].G(), h = 0; h < g.length; h++) e.push(nueva T(c, g[h])); return e }; función bb(a, b) { esto.b = a; this.h = b; this.g = La(this.b, "span", { "aria-hidden": "true" }, this.h) } function cb(a) { Ma(ab, "body", ag) } function db(a) { return "display: block; posición: absolute; superior: -9999px; izquierda: -9999px; font-size: 300px; width: auto; height: auto; line- altura: normal; margen: 0; relleno: 0; fuente-variante: normal; espacio en blanco: nowrap; fuente-familia: " + Xa(ah) + "; " + (" tipo de letra: " + Wa(a) + "; font-weight:" + (a.g + "00") + ";") }; función eb(a, b, c, d, e, f, g) {
this.H = a; this.L = b; this.b = c; this.g = d; this.C = g || "BESbswy"; this.h = {}; this.S = e || 3E3; this.J = f | | nulo; esto.A = this.w = this.u = this.m = null; this.m = new bb(this.b, this.C); this.u = new bb(this.b, this.C); this.w = new bb(this.b, this.C); this.A = new bb(this.b, this.C); a = new T(this.g.getName() + ", serif", S(this.g)); a = db(a); this.mgstyle.cssText = a; a = new T(this.g.getName() + ", sans-serif", S(this.g)); a = db(a); this.ugstyle.cssText = a; a = new T("serif", S(this.g)); a = db(a); this.wgstyle.cssText = a; a = new T("sans-serif",
    S(this.g)) a = db(a); this.Agstyle.cssText = a; cb(this.m); cb(this.u); cb(this.w); cb(this.A)
} var fb = { Y: "serif", X: "sans-serif" }, gb = null; function hb() { if (null === gb) { var a = / AppleWebKit \ /([0 - 9] +)(?: \.([0 - 9] +)) /.Exec(window.navigator.userAgent); gb = !!a && (536 > parseInt(a[1], 10) || 536 == = parseInt(a[1], 10) && 11 > = parseInt(a[2], 10)) } devolver gb } eb.prototype.start = function () { this.h.serif = this.wgoffsetWidth; this.h["sans-serif"] = this.AgoffsetWidth; this.K = m(); ib(this) };
función jb(a, b, c) { para(var d en fb) if (fb.hasOwnProperty(d) && b === ah[fb[d]] && c === ah[fb[d]]) return !0; return !1 } función ib(a) { var b = amgoffsetWidth, c = augoffsetWidth, d; (d = b === ahserif && c === ah["sans-serif"]) || (d = hb() && jb(a, b, c)); d ? m() - aK > = aS ? hb() && jb(a, b, c) && (null === aJ || aJhasOwnProperty(aggetName())) ? kb(a, aH) : kb(a, aL) : lb(a): kb(a, aH) } función lb(a) { setTimeout(k(function () { ib(this) }, a), 50) ) }
function kb(a, b) { setTimeout(k(function () { Oa(this.mg); Oa(this.ug); Oa(this.wg); Oa(this.Ag); b(this.g) }, a), 0) }; función mb(a, b, c, d, e, f) { this.m = a; this.w = b; this.g = d; this.b = c; this.h = e || 3E3; this.u = f || void 0 } mb.prototype.start = function () { var a = this.bgdocument, b = this, c = m(), d = new Promise(función(d, e) { función h() { m() - c > = bh ? e() : a.fonts.load(Va(bg), bu).then(función(a) { 1 <= a.length ? d() : setTimeout(h, 25) }, function () { e() })} h()}), e = new Promise(function (a, c) { setTimeout(c, bh) }); Promise.race([e, d]).Then(function () { bm(bg) }, function () { bw(bg) })}; function nb(a, b, c) { this.b = a; this.g = b; this.h = 0; this.A = this.w = !1; this.C = c } var ob = null; nb.prototype.m = function (a) { var b = this.g; bm && Q(bh, [bgs("wf", a.getName(), S(a).toString(), "active")], [bgs("wf", a.getName(), S(a).toString(), "cargando"), bgs("wf", a.getName(), S(a).toString(), "inactivo"))) R(b, "fontactive", a); this.A = !0; pb(this) };
nb.prototype.u = función(a) { var b = this.g; if (bm) { var c = Pa(bh, bgs("wf", a.getName(), S(a).toString(), "activo")), d = [], e = [bgs("wf", a.getName(), S(a).toString(), "loading")]; c || d.push(bgs("wf", a.getName(), S(a).toString(), "inactivo")); Q(bh, d, e) } R(b, "fontinactive", a); pb(esto) }; función pb(a) { 0 == - ah && a.w && (aA ? (a = ag, am && Q(ah, [ags("wf", "active")], [ags("wf", "loading "), ags(" wf ", " inactivo ")]), R(a, " activo ")) : Ua(ag)) }; función qb(a, b) { this.m = a; this.b = b; this.g = [] } qb.prototype.h = function (a) { this.g.push(a) }; qb.prototype.load = function (a, b) { var c = a, d = b || {}; "cadena" == tipo de c ? c = [c] : c && c.length || (d = c || {}, c = []); if (c.length) para(var e = esto, f = c.length, g = 0; g < c.length; g++) rb(esto, c[g], función() { 0 === - f && sb(e, d) }); else sb(this, d) }; función rb(a, b, c) { b = ams({ id: encodeURIComponent(b) }); Sa(ab, b, c) }
función sb(a, b) { if (0! == aglength) { para(var c = new Ta(ab, b), d = !1, e = 0; e < aglength; e++) ag[e].init(), d = d || ag[e].supportsConfiguredBrowser(); if (d) para(cm && Q(ch, [cgs("wf", "loading"))), R(c, "loading"), c = 0; c < aglength; c++) d = ag[c], d.supportsConfiguredBrowser() && d.load(null, c == aglength - 1, b); else Ua(c); ag = [] } }; función tb() { this.g = 0; this.b = null } function ub(a) { a.g++; return function () { ag -; vb(a) } } function wb(a, b) { ab = b; vb(a) } función vb(a) { 0 == ag && a.b && (ab(), ab = null) }; función xb(a, b) { this.b = b || Array(Math.ceil(a / 32)); if (!B) para(var c = 0; c < this.b.length; c++) this.b[c] = 0 }; función U(a, b) { return (a & 65535) * b + (((a >>> 16) * b & 65535) << 16) }; función yb(a, b, c) { this.b = a; this.h = b; this.g = nuevo xb(a, c) } var zb = [2449897292, 4218179547, 2675077685, 1031960064, 1478620578, 1386343184, 3194259988, 2656050674, 3012733295, 2193273665]; función Ab() {
    var a; a = Bb; if (window.atob) a = window.atob(a); else { a = a.replace(/ = + $ /, ""); si(1 == a.length % 4) arrojó un error("'atob' falló: la cadena a descodificar no está codificada correctamente."); para(var b = 0, c, d, e = 0, f = ""; d = a.charAt(e++); ~d && (c = b % 4 ? 64 * c + d : d, b++ % 4) ? F + = String.fromCharCode(255 & c >> (- 2 * b & 6)): 0) d = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 + /".indexOf(d); a = f } c = []; for (b = 0; b < a.length; b + a y) .charCodeAt(b) << 24 | a.charCodeAt(b + 1) << 16 | a.charCodeAt(b + 2) << 8 | a.charCodeAt(b + 3) << 0); a = c.cambio(); La cadena a decodificar no está codificada correctamente. "); Para (var b = 0, c, d, e = 0, f =" "; d = a.charAt (e ++); ~ d && (c = b% 4 ? 64 * c + d: d, b ++% 4)? F + = String.fromCharCode (255 & c >> (- 2 * b & 6)): 0) d = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123478788789 / /. c = []; para (b = 0; b <a.length; b + = 4) c.push (a.charCodeAt (b) << 24 | a.charCodeAt (b + 1) << 16 | a.charCodeAt (b + 2) << 8 | a.charCodeAt (b + 3) << 0); a = c.shift ();La cadena a decodificar no está codificada correctamente. "); Para (var b = 0, c, d, e = 0, f =" "; d = a.charAt (e ++); ~ d && (c = b% 4 ? 64 * c + d: d, b ++% 4)? F + = String.fromCharCode (255 & c >> (- 2 * b & 6)): 0) d = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123478788789 / /.c =[]; para(b = 0; b < a.length; b + = 4) c.push(a.charCodeAt(b) << 24 | a.charCodeAt(b + 1) << 16 | a.charCodeAt(b + 2) << 8 | a.charCodeAt(b + 3) << 0); a = c.shift(); 8 | a.charCodeAt(b + 3) << 0); a = c.shift(); 8 | a.charCodeAt(b + 3) << 0); a = c.shift();
    b = c.shift(); this.b = new yb(a, b, c)
}
función Cb(a) {
    para(var b = location.hostname.split("."); 0! == b.length;) {
        var c; a: {
            c = ab; var d = b.join(" . "); if (" string "! == typeof d && " number "! == typeof d) arroja Error(" El valor debe ser una cadena o un número. "); for (var e = " number " === typeof d, f = 0; f < ch; f++) {
                var g = 0; si(e) var g = zb[f] || 0, h = d & 4294967295, h = U(h, 3432918353), h = h < < 15 | h >>> 17, h = U(h, 461845907), g = g ^ h, g = g << 13 | g >>> 19, g = U(g, 5) + 3864292196, g = g ^ 4; else {
                    for (var g = zb[f] || 0, l = h = 0, p = d.length % 4, z = d.length - p, l = 0; l < z; l + = 4) h = (d.charCodeAt(l + 0) & 4294967295) << 0 | (d.charCodeAt(l +
                        1) & 4294967295) << 8 | (d.charCodeAt(l + 2) & 4294967295) << 16 | (d.charCodeAt(l + 3) & 4294967295) << 24, h = U(h, 3432918353), h = h << 15 | h >>> 17, h = U(h, 461845907), g ^ = h, g = g << 13 | g >>> 19, g = U(g, 5) + 3864292196; h = 0; switch (p) {caso 3: h ^ = (d.charCodeAt(l + 2) & 4294967295) << 16; caso 2: h ^ = (d.charCodeAt(l + 1) & 4294967295) << 8; caso 1: h ^ = (d.charCodeAt(l + 0) & 4294967295) << 0, h = U(h, 3432918353), h = h << 15 | h >>> 17, h = U(h, 461845907), g ^ = h
                } g ^ = d.length
            } g ^ = g >>> 16; g = U(g, 2246822507); g ^ = g >>> 13; g = U(g, 3266489909); g ^ = g >>> 16; g = (g >>> 0) % cb; h = cg; si(Math.floor(g / 32 + 1) > hblength) produce un error("El índice está fuera de los límites". );
            l = Math.floor(g / 32); if (!(hb[l] & 1 << g - 32 * l)) { c = !1; break a }
        } c = !0
    } si(c) regresa! 0; b.shift()
} devuelve! 1}; función Db(a) { this.b = a; this.g = "x"; this.C = this.L = null; this.h = []; this.m = []; this.H = this.u = null; this.J = !1; this.w = null; this.A = !1 } Db.prototype.supportsConfiguredBrowser = function () { return "x "! == this.g }; Db.prototype.init = function () { if (0 < this.m.length) { for (var a = [], b = 0; b < this.m.length; b++) a.push(ea(this.m[b])); var b = this.b, a = a.join(""), c = La(this.b, "style"); c.setAttribute("tipo", "texto / css"); c.styleSheet ? c.styleSheet.cssText = a : c.appendChild(document.createTextNode(a)); Ma(b, "head", c) } };
Db.prototype.load = function (a, b, c) {
    function d() { } var e = this, f = c || {}, g = f.contextPath || ".", H = f.hostname || this.H; a = f.timeout; c = !!f.async; var l = !1! == f.events, p = null, z = new la, H = new la, G = new tb; f.active && (d = f.active); f.active = function () {
        Hb = (nueva fecha) .getTime(); if (eK) {
            var a = eK, b = -1! == zg && - 1! == zb ? Zb - zg : -1, c = -1! == Hg && - 1! == Hb ? Hb - Hg : -1, f = eA, g = new oa("// p.typekit .net / p.gif? s = {service} & k = {token} & app = {app} & ht = {hosting} & h = {host} & f = {variaciones} & a = {account} & sl = {stylesheetLoadTime} & fl = { fontLoadTime} & dc = {domainCheck} & js = {version} & _ = {_} "),
            h = encodeURIComponent((window.__ adobewebfontsappname__ || a.app || "").toString().substr(0, 20)), l = encodeURIComponent(ga(eb)), r = [], p = []; window.Typekit.fonts || (window.Typekit.fonts = []); para(var p = window.Typekit.fonts, u = 0; u < ablength; u++) { for (var G = !1, I = 0; I < p.length; I++) if (ab[u] === p[I]) { G = !0; break } G || (r.push(ab[u]), p.push(ab[u])) } r.length && qa(gs({ service: am, token: au, app: h, hosting: ah, host: l, variaciones: r.join("."), cuenta: ag, stylesheetLoadTime: b, fontLoadTime: c, domainCheck: f, versión: a.version, _: (+ nueva fecha).toString()}))
    } d()
};
p = nueva Ta(this.b, f); null! == this.w ? Cb(this.w) && (this.A = !0) : this.A = !0; if (this.g) {
    para(var f = na[this.g] || new ja(ka), u = 0; u < this.h.length; u++) Za(this.h[u], this.g, f); this.u && (f = ma(this.b, this.g, this.h), f = pa(this.g, f), f.contextPath = g, h && (f.hostname = h), g = this.us(f, this.J ? "https:"! == Qa(this.b) : !1), z.start(), Ra(this.b, g, ub(G), c)); if (l) {
        for (var I = [], ab = {}, r = new nb(this.b, p, a), u = 0; u < this.h.length; u++) I = I.concat($ a(this.h[u], this.g)); para(u = 0; u < I.length; u++) ab[I[u].getName()] = "BESbswy \ ue000 \ ue001 \ ue002 \ ue003 \ ue004 \ ue005 \ ue006 ";
        wb(G, function () { zb = (nueva fecha).getTime(); H.start(); Na(eb, function () {
            var a = I, c = {}, d = ab || {}; if (0 === a.length && b) Ua(rg); else {
            r.h + = a.length; b && (rw = b); var e, f = []; for (e = 0; e < a.length; e++) {
                var g = a[e], h = d[g.getName()], l = rg, p = g; lm && Q(lh, [lgs("wf", p.getName(), S(p).toString(), "loading")]); R(l, "fontloading", p); l = null; null === ob && (ob = window.FontFace ? (P = / Gecko. * Firefox \ /(\ d +) /.Exec(window.navigator.userAgent)) ? 42 < parseInt(p[1], 10) : !0 : !1); ob ? L = new mb(k(rm, r), k(ru, r), rb, g, rC, h) : l = nuevo eb(k(rm, r), k(ru, r),
                    rb, g, rC, c, h); f.push(l)
            } para(e = 0; e < f.length; e++) f[e].start()
    }
})})}} var ; Eb, O = nueva función() { var a = documento; this.b = navigator.userAgent; this.g = a }, Fb;
if (-1! = ObindexOf("MSIE") || -1! = ObindexOf("Trident /")) { var V = O, Gb = L(V), Hb = C(N(V)), Ib = nulo, Jb = nulo, Kb = nulo, Lb = M(Vb, / Trident \ /([\ d \ w \.] +) /, 1), Mb = P(Vg), Ib = -1! = VbindexOf ("MSIE") ? C(M(Vb, / MSIE ([\ d \ w \.] +) /, 1)) : C(M(Vb, / rv: ([\ d \ w \.] +) /, 1)); ""! == ¿Lb ? (Jb = "Trident", Kb = C(Lb)) : (Jb = "Unknown", Kb = new x); Fb = new w("MSIE ", Ib, Jb, Kb, Gb, Hb, Mb) } else {
    var Nb; if (-1! = ObindexOf(" Edge / ")) { var Ob = O, Pb = L(Ob), Qb = C(N(Ob)), Rb = C(M(Ob.b, / Edge \ /([\ d \ w \.] +) /, 1)); Nb = new w("Edge", Rb, " Borde ", Rb, Pb, Qb, P(Ob.g)) } else {
        var Sb; if (-1! =
            ObindexOf("Opera")) Sb = Ha(); else { var Tb; if (/ OPR \ /[\ d.]+ /. Prueba (Ob)) Tb = Ia (); else {var Ub; if ( /AppleWeb(K | k)it /.test(Ob)) Ub = Ia();else { var Vb; if (-1! = ObindexOf("Gecko")) { var W = O, Wb = "Desconocido", Xb = nuevo x, Yb = C(N(W)); - 1! = WbindexOf("Firefox") ? (Wb = "Firefox", Xb = C(M(Wb, / Firefox \ /([\ d \ w \.] +) /, 1))) : - 1! = WbindexOf("Mozilla") && (Wb = "Mozilla"); var Zb = C(M(Wb, / rv: ([^ \) ] +) /, 1)); Vb = nuevo w(Wb, Xb, "Gecko", Zb, L(W), Yb, P(Wg)) } else Vb = Ga; Ub = Vb } Tb = Ub } Sb = Tb
    } Nb = Sb
} Fb = Nb} Eb = Fb;
var $ b = nueva función () { var a = ventana; this.g = this.h = a; this.b = this.g.document }; window.Typekit || (window.Typekit = {}); if (!window.Typekit.load) { var ac = window.Typekit.config || {}, bc = null; ac.k && (bc = new oa(ac.k)); var cc = new qb(bc, $ b); window.Typekit.load = function () { cc.load.apply(cc, argumentos) }; window.Typekit.addKit = function () { cc.h.apply(cc, argumentos) } } var dc, X, Y, n = window.Typekit.config || {}; Y = nueva Db($ b);
YK = nueva función() { var a = n.ht, b = n.fi, c = na, d = n.kt, e = n.js, f = nl; this.m = n.ps; esto.h = a; this.b = b || []; this.g = c || null; this.u = d || null; this.version = e || null; this.app = f || null }; X = nuevo ca; XO = !N.si; XN = !N.st; XI = !N.sa; XR = !N.sw; XP = !N.sb; YC = X; if (n.dl) { var Bb = n.dl; intente { Yw = nuevo Ab } catch (a) { } } n.ds && (YJ = n.ds); nf && (dc = new oa(nf), Yu = dc); n.hn && (YH = n.hn); var q; if (n.fn) para(q = 0; q < n.fn.length; q + = 2) Yhpush(nuevo Ya(n.fn[q], n.fn[q + 1])); if (nc) para(q = 0; q < nclength; q + = 2) Ympush(new da); YL = Eb; var ec;
a: { var fc = YL, gc = nuevo ca, hc = YC || gc, ic; para(ic en t) { var Z = t[ic]; if (Fa[Z] && Fa[Z](fc, hc)) { ec = Z; rompe a } } para(ic en t) si(Z = t[ic], Fa[Z] && Fa[Z](fc, gc)) { ec = "x"; } ec = "k" } Yg = ec; window.Typekit.addKit(Y); si(window.WebFont) intente { window.Typekit.load() } catch (a) { };} (este, documento));

intente { Typekit.load(); } catch (e) { };